aarch64:
  - 'aarch64-linux-gnu-gcc'
  - '-mcmodel=small -shared -g -fPIC'
  - 'aarch64-linux-gnu-objcopy'
  - 'aarch64-linux-gnu-strip'
  - null
  - false
powerpc64:
  - 'powerpc64-linux-gnu-gcc'
  - '-g -shared'
  - 'powerpc64-linux-gnu-objcopy'
  - 'powerpc64-linux-gnu-strip'
  - '{}/..'
  - true
mips64:
  - 'mips64-linux-gnuabi64-gcc'
  - '-g -shared'
  - 'mips64-linux-gnu-objcopy'
  - 'mips64-linux-gnu-strip'
  - '{}/..'
  - false
riscv64:
  - 'riscv64-linux-gnu-gcc'
  - '-g -fPIC -shared'
  - 'riscv64-linux-gnu-objcopy'
  - 'riscv64-linux-gnu-strip'
  - null
  - false
x86_64:
  - 'gcc'
  - '-g -fPIC -shared'
  - 'objcopy'
  - 'strip'
  - null
  - false
